version: "3"  # optional since v1.27.0
services:
  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_DB_CONNECTION_STRING=
      - MONGO_DB_NAME=
      - REDIS_URI=